project:
  type: website
  render:
    - "*.qmd"
    - "posts/*.ipynb"
    - "posts/*/*.ipynb"
    - "!posts/post-with-code"
    - "!posts/welcome"


website:
  title: "Sajjan Acharya"
  navbar:
    right:
      - about.qmd
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



